### ISSUE TITLE
Use theon as low level HTTP engine

### ISSUE THREAD

**Issue by h2non** [zzarcon/nodegram#1]
theon provides all the needs to create an extensible API in a declarative way with built-in support to path params parsing, promises, hooks (then you can define the auth token dynamically) and more.

It has been used in production for a while in both node.js ans front end apps.
https://github.com/h2non/theon

**Comment by zzarcon** [comment]
Yeah!

I'd like to replace superagent for theon :+1: 

Do you mind to open a PR in order to do that?

**Comment by h2non** [comment]
Cool. Would you mind create a specific brand for feature? Then I can do the PR.
